# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "manager" do |manager|
    manager.vm.box = "centos/7"
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.1.15"
    manager.vm.provision "shell", path: "provision.sh"
    # manager.vm.provision "file", 
    #   source: "/home/renatodevops/Development/Learn/DevOps_handsOn/new_handson/k3s_lab/registries.yaml", 
    #   destination: "/vagrant/registries.yaml"
    manager.vm.provider "virtualbox" do |mprovider|
      mprovider.memory = 6144
      mprovider.cpus = 2
    end
    manager.vm.network "forwarded_port", guest: 80, host: 80
    manager.vm.network "forwarded_port", guest: 6443, host: 6443
    for p in 30000..30100
      manager.vm.network "forwarded_port", guest: p, host: p, protocol: "tcp"
    end
  end
  
end
