---
- name: configurar servidor de aplicacao Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    dbhost: "db01"
    dbname: "notes"
    dbusername: "notesapp"
    dbpassword: "devops123"
  tasks:
    - name: Adicionar usuario de app
      user:
        name: app
        comment: Usuario de aplicação
        uid: 500
    - name: Donwload do maven 
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz
    - name: Unzip do pacote maven
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Instalação do Java
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: Criação do diretório de app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: instalacao do git client
      yum:
        name: git
        state: latest
    - name: clone do repositorio Notes - app
      git:
        # repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        repo: https://github.com/renatoDev0ps/spring-boot-mysql-rest-api-tutorial.git
        dest: /opt/notes
        clone: yes
        force: yes
    # - name: Configurar arquivo pom.xml com repositorios maven central
    #   template:
    #     src: pom.xml
    #     dest: /opt/notes/pom.xml
    - name: configurar arquivo de propriedade para camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: gerar pacote da aplicacao
      # command: mvn -f /opt/notes/pom.xml package
      command: /opt/apache-maven-3.1.0/bin/mvn -f /opt/notes/pom.xml package
      become_user: app
    - name: registrar a versao atual do pacote
      shell:
        # command: mvn -o -q -Dexec.executable=echo -Dexec.args='${project.version}' exec:exec
        cmd: /opt/apache-maven-3.1.0/bin/mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: /opt/notes/
      register: app_version
    - name: configurar serviço do systemd
      template:
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
        # owner: root
        # group: root
        # mode: '0600'
      notify: reload daemon
    - name: iniciar servico notes
      service:
        name: notes
        state: restarted
  roles:
    - configuracao-default-so
    # - role: gantsign.maven
    #   maven_version: '3.2.5'
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes
