Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "nexus"
  config.vm.network "forwarded_port", guest: 8082, host: 8082, hostip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8123, host: 8123, hostip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.1.10"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

end