Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
    vb.linked_clone = true
    vb.customize ['modifyvm', :id, '--audio', 'none']
  end
  
  boxes = [
    { :name => "kube0", :ip => "192.168.1.11" },
    { :name => "kube1", :ip => "192.168.1.12" },
    { :name => "kube2", :ip => "192.168.1.13" },
    { :name => "kube3", :ip => "192.168.1.14" },
  ]
  
  boxes.each_with_index do |opts, index|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:ip]
    end
  end
  
end